# Generated by Django 5.1.2 on 2024-10-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('type_field', models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Car', 'Car'), ('Other', 'Other')], max_length=50)),
                ('bathrooms', models.IntegerField(default=1)),
                ('bedrooms', models.IntegerField(default=1)),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
        ),
    ]
